### ISSUE TITLE
[PHP] Webman is failing

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3921]
Hi @walkor,

I've updated CI (I notice it was useless) and then it appear that `webman` is failing

https://github.com/the-benchmarker/web-frameworks/runs/1845194240?check_suite_focus=true#step:7:10

Regards,

/cc @RicardoSette

**Comment by RicardoSette** [comment]
Hi @walkor ,

The error may be in relation to the Dockerfile, because here it did not compile with the dependency libevent-dev

In local tests without libevent-dev OK, see:

POST with body empty in request OK
> $ curl -X POST -d '' -i 127.0.0.1:87/user/0 
> HTTP/1.1 200 OK
> Server: workerman
> Connection: keep-alive
> Content-Type: text/html;charset=utf-8
> Content-Length: 1
> 
> 0


GEY /user/0 OK
> $ curl -X GET -i 127.0.0.1:87/user/0
> HTTP/1.1 200 OK
> Server: workerman
> Connection: keep-alive
> Content-Type: text/html;charset=utf-8
> Content-Length: 1
> 
> 0


GET /user OK
> $ curl -X GET -i 127.0.0.1:87/user
> HTTP/1.1 200 OK
> Server: workerman
> Connection: keep-alive
> Content-Type: text/html;charset=utf-8
> Content-Length: 0
> 
>

**Comment by walkor** [comment]
> Only error in POST without body.

If the `content-length` header is missing in the post request, it will be considered illegal for workerman.

I noticed failing message in CI.
```
Failures:

  1) routes GET : /user/0 returns the expected param
     Failure/Error: expect(response.body).to eq('0')

       expected: "0"
            got: ""
```
But I tested many times in local and it works fine for me.
